### ISSUE TITLE
plugins/logging/viewerrecorder.cpp is incompatible with FFmpeg v5

### ISSUE THREAD

**Issue by cielavenir** [rdiankov/openrave#1264]
https://github.com/rdiankov/openrave/blob/production/plugins/logging/viewerrecorder.cpp

cf https://github.com/rdiankov/openrave/pull/1263#issuecomment-1601093389

**Comment by cielavenir** [comment]
@felixvd could you start to take a look? we should complete this by 2025 June.

**Comment by hemangandhi** [comment]
Branch: https://github.com/rdiankov/openrave/tree/1264-ffmpeg5-compat

**Comment by cielavenir** [comment]
merged :tada:
