### ISSUE TITLE
anyone could please give a  complete link of openrave for python3?

### ISSUE THREAD

**Issue by flydragon2018** [rdiankov/openrave#1301]
I  searched around, found some discussions about it.

but couldn't find a complete working guide for installation openrave for python3.

**Comment by cielavenir** [comment]
now openrave should build python3 by default, if pybind11 is installed

**Comment by flydragon2018** [comment]
thanks for your reply.  I didn't find the official document.

**Comment by WenzheHe** [comment]
@flydragon2018 Hello, have you successfully installed openrave for python3?
