### ISSUE TITLE
Incorrect rpath on openravepy_configurationcache.so

### ISSUE THREAD

**Issue by mkoval** [rdiankov/openrave#321]
I get this warning with the latest master:

    [plugindatabase.h:929 _SysLoadLibrary] /usr/share/openrave-0.9/plugins/openravepy_configurationcache.so: openravepy_int.so: cannot open shared object file: No such file or directory
    [plugindatabase.h:857 _LoadPlugin] failed to load: /usr/share/openrave-0.9/plugins/openravepy_configurationcache.so

`ldd` shows that it's actually failing to load both `openravepy_int.so` and `libconfigurationcache.so`. It loads without any warnings if I add those parent directories to my `LD_LIBRARY_PATH`. Therefore, it looks like `openravepy_configurationcache.so` is being built with the wrong RPATH.

You're linking with those libraries using `target_link_libraries`, so I'm not sure why CMake isn't setting the correct RPATH during the installation step.

**Comment by AbdealiJK** [comment]
I have the same issue on Ubuntu 14.04.2

**Comment by rdiankov** [comment]
hi all,
finally got around to fixing the openravepy_configurationcache dir. it is not installed inside python and not in the plugindir, i do add plugins dir INSTALL_RPATH

e06caacdcbdc9c48b481b04909b2d0529c7eaa98

thanks to all for pointing this out!
