### ISSUE TITLE
Make march=native user-definable

### ISSUE THREAD

**Issue by languitar** [rdiankov/openrave#358]
Since the addition of `march=native` to the compile flags, we are unable to build openrave so that different processors are supported. Moreover, due to a qemu bug, compilation even fails on a VM. I can understand why this is generally a desired setting in case you optimize the builds specifically for a machine, but in terms of more generic packaging, this breaks many things. Therefore, please provide a CMake option to make this behavior optional.

**Comment by rdiankov** [comment]
good point, just made it so that NATIVE_COMPILE_FLAGS is empty by default

c5e7599b3e302a2aacea43b82f97abf9fd3a04fe

**Comment by rdiankov** [comment]
just curious, can you tell me what the errors were? it's hard to imagine how march=native can break builds.
thanks

**Comment by languitar** [comment]
Thanks. We endet up in exactly this:
http://dpdk.org/ml/archives/dev/2014-June/003748.html

**Comment by languitar** [comment]
Could you please apply the fix also to latest_stable?

**Comment by rdiankov** [comment]
np, done ;0)
