### ISSUE TITLE
build fails using make -j1

### ISSUE THREAD

**Issue by jon-weisz** [rdiankov/openrave#363]
If forced to build single threaded, the build fails. While not a common use case, this points to some fundamental brittleness in the CMakeFile, probably with setting build dependencies that enforce ordering when building 3rd part libraries. 

The final error message is:
[16%] Building CXX object src/libopenrave/CMakeFiles/libopenrave.dir/libopenrave.cpp.o
/tmp/jenkins/jobs/openrave-master-toolkit-cca-lwr-testing-nightly/workspace/src/libopenrave/libopenrave.cpp:62:33: fatal error: /tmp/jenkins/jobs/openrave-master-toolkit-cca-lwr-testing-nightly/workspace/build/src/libm_accuracy_results.h: No such file or directory
 #include LIBM_ACCURACY_RESULTS_H
                                 ^

See https://gist.github.com/jon-weisz/146082b79e7835568157 for full details

I am investigating this error and will PR a fix when I get to the bottom of it. If this is a known bug or an error on my part, let me know and I will just work around it.

**Comment by rdiankov** [comment]
great spot! a recent change had broken the dependency setting, it should be fixed now:

5466938a125eafce91fad92cbd83c9d870088103

please check it out.
thanks
