### ISSUE TITLE
undefined symbols in libqtosgrave

### ISSUE THREAD

**Issue by morxa** [rdiankov/openrave#426]
There are multiple undefined symbols in libqtosgrave so it's impossible to load the plugin:

    $  openrave
    2016-08-01 12:09:30,476 openrave [WARN] [plugindatabase.h:929 RaveDatabase::_SysLoadLibrary] /usr/lib64/openrave/plugins/libqtosgrave.so: /usr/lib64/openrave/plugins/libqtosgrave.so: undefined symbol: _ZN9qtosgrave11QtOSGViewer11multiWidgetEv

Looking at the source code, I can find a [declaration for `multiWidget()`](https://github.com/rdiankov/openrave/blob/master/plugins/qtosgrave/qtosgviewer.h#L141), but there is no definition in qtosgviewer.cpp or anywhere else. Also, it seems like the function is never used anywhere, but I don't know much about Qt slots.

I'm not sure where the symbol should come from, so this might be a build issue.

**Comment by rdiankov** [comment]
just removed it, good catch! my gcc doesn't complain, so let me know if there's more unused functions.

thanks
