### ISSUE TITLE
C++ in C API

### ISSUE THREAD

**Issue by sirop** [rdiankov/openrave#466]
If you look through https://github.com/rdiankov/openrave/blob/master/src/libopenrave/libopenrave_c.cpp,
you'll find things like default functions values  and bool data type which are valid in C++, but not in C.

I made some cleanup  https://github.com/sirop/openrave/commit/3e4035385a81a92f36fb3860f8a8ab09ca6a64fd .
That's good enough for my needs, as I can use gcc instead of g++ now.

Saw also that C API is used in C# examples.
Is this the only reasoning for C++ remnants in C API?

**Comment by rdiankov** [comment]
thanks! can you send a pull request?
the C API is only to get C compatible function signatures to do foreign function interchange between various languages, but i have no problem if you want to help get a C compiler to work on it.
best,

**Comment by sirop** [comment]
I'll do a proper commit in the next days as https://github.com/sirop/openrave/commit/3e4035385a81a92f36fb3860f8a8ab09ca6a64fd does not contain the C API changes within https://github.com/rdiankov/openrave/tree/master/src/csharpbindings_c .

**Comment by sirop** [comment]
Closed via https://github.com/rdiankov/openrave/pull/468 .
