### ISSUE TITLE
cannot run openrave.py --example graspplanning

### ISSUE THREAD

**Issue by nag92** [rdiankov/openrave#519]
I am trying to install openrave on 16.04. I followed the instructions here: https://scaron.info/teaching/installing-openrave-on-ubuntu-16.04.htm

when I try to run the example the window opens for a second then it crashes and I get the following error:

`osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/segwayrmp/segwayrmp.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/segwayrmp/segwayrmp.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/WAM/wam0.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/WAM/wam0.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/WAM/wam1.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/WAM/wam1.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/WAM/wam2.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/WAM/wam2.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/WAM/wam3.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/WAM/wam3.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/WAM/wam4.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/WAM/wam4.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/WAM/wam5.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/WAM/wam5.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/WAM/wam6.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/WAM/wam6.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/WAM/wam7_nohand.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/WAM/wam7_nohand.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/palm.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/palm.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link1.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link1.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link1.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link1.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link2.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link2.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link3.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link3.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link1.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link1.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link2.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link2.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link3.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link3.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link2.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link2.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/barrett/link3.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/barrett/link3.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/segwayrmp/segwayrmp.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/segwayrmp/segwayrmp.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv loaded successfully.
osgDB::ReaderWriterIV::readNode() Reading file /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv
osgDB::ReaderWriterIV::readNode() File /usr/local/share/openrave-0.9/models/objects/blue_mug_y_up.iv loaded successfully.
openravepy.databases.inversekinematics: GetDefaultIndices, found 3-intersection centered on index 1
openravepy.databases.inversekinematics: GetDefaultIndices, found 3-intersection centered on index 5
robot resolutions:  [ 0.00396017  0.00455076  0.00593835  0.00951787  0.01218716  0.0175349
  0.02203869  0.0606854   0.0606854   0.0606854   0.04497103]
robot weights:  [ 2.77253268  2.41271402  1.84894655  1.15358696  0.90092279  0.62616198
  0.49820064  0.18092804  0.18092804  0.18092804  0.24415027]
searching for graspable objects (robot=42daa21cdb5bcad0df5d94673fd5d61a)...
mug1 is graspable
mug2 is graspable
mug3 is graspable
mug4 is graspable
mug5 is graspable
mug6 is graspable
searching for destinations on table...
Traceback (most recent call last):
  File "/usr/local/bin/openrave.py", line 149, in <module>
    example.run(args=args)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/openravepy_ext.py", line 64, in newfn
    return fn(*args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/examples/graspplanning.py", line 476, in run
    OpenRAVEGlobalArguments.parseAndCreateThreadedUser(options,main,defaultviewer=True)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/misc.py", line 240, in parseAndCreateThreadedUser
    SetViewerUserThread(env,viewername,lambda: userfn(env,options))
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/misc.py", line 100, in SetViewerUserThread
    userfn()
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/misc.py", line 240, in <lambda>
    SetViewerUserThread(env,viewername,lambda: userfn(env,options))
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/examples/graspplanning.py", line 452, in main
    self = GraspPlanning(robot,randomize=options.randomize,nodestinations=options.nodestinations,plannername=options.planner)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/examples/graspplanning.py", line 169, in __init__
    alldests = self.setRandomDestinations([graspable[0].target for graspable in needdests_graspables],table)
  File "/usr/local/lib/python2.7/dist-packages/openravepy/_openravepy_0_9/examples/graspplanning.py", line 242, in setRandomDestinations
    X = r_[X, tile((x+1)/(Nx+1),Ny)]
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/shape_base.py", line 881, in tile
    return c.reshape(shape_out)
TypeError: 'numpy.float64' object cannot be interpreted as an index
QThreadStorage: Thread 0x7f5ee000f540 exited after QThreadStorage 8 destroyed
QThreadStorage: Thread 0x7f5ee000f540 exited after QThreadStorage 7 destroyed
QThreadStorage: Thread 0x7f5ee000f540 exited after QThreadStorage 4 destroyed
QThreadStorage: Thread 0x7f5ee000f540 exited after QThreadStorage 3 destroyed
QThreadStorage: Thread 0x7f5ee000f540 exited after QThreadStorage 2 destroyed
QThreadStorage: Thread 0x7f5ee000f540 exited after QThreadStorage 1 destroyed`
 
I am not sure how to fix this. I am guessing I am missing a dependency.
Can any one help me?

**Comment by cielavenir** [comment]
Fixed in latest production
