### ISSUE TITLE
[ikfast] Controlling number of solutions and enforcing joint limitations

### ISSUE THREAD

**Issue by hamzamerzic** [rdiankov/openrave#537]
Hi. I am wondering if there is a way to control the number of solutions provided by ikfast and enforce joint limitations? 
Currently I either get 0 or 8 solutions, and in case I get solutions, a lot of them fall out of the allowed joint range.

Thanks!

**Comment by rdiankov** [comment]
At the moment, ikfast does not encode joint limits, so you'll have to check the joint limits once all the solutions have been computed.

**Comment by hamzamerzic** [comment]
Thanks for quick reply @rdiankov! I am also curious about increasing the number of solutions. Is that possible?

**Comment by Ahrimanox** [comment]
Hi. I'm also interested about why does ikfast only returns 0, 4 or 8 joint solutions.
I haven't found any reasons or discussions about that !
