### ISSUE TITLE
CMake fails on fclrave (Ubuntu 16.04)

### ISSUE THREAD

**Issue by haudren** [rdiankov/openrave#633]
I'm running Ubuntu 16.04 and updated OpenRAVE, it now fails to compile with this error:
```
CMake Error at plugins/fclrave/CMakeLists.txt:77 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
-- Configuring incomplete, errors occurred!
```

After a little bit of bisection, it seems that 28117646f6e28d7c02dc2148b2ce39b32b71dbe1 is the cause of the issue, and those quotes *were* necessary: my `FCL_LDFLAGS` only contains `-lfcl` (unquoted) which triggers the error as it's interpreted as an extra argument instead of being appended to `PLUGIN_LINK_FLAGS`.

**Comment by piraka9011** [comment]
I also had this issue. Reverted the changes of the commit and it works fine for me. Maybe revert #611 in master?
