### ISSUE TITLE
can't run python examples, undefined symbol  _ZTIN8OpenRAVE17OpenRAVEExceptionE

### ISSUE THREAD

**Issue by huiwenzhang** [rdiankov/openrave#936]
- Ubuntu: 16.06
- compile install

I compiled the package from source and it can be successfully compiled, However, when I run the python examples, it throws error:
```
/openravepy/_openravepy_/convexdecompositionpy.so: undefined symbol: _ZTIN8OpenRAVE17OpenRAVEExceptionE
/openravepy/_openravepy_/pyANN_int.so: undefined symbol: _ZTIN8OpenRAVE17OpenRAVEExceptionE
```
How to fix this?

Thanks,

**Comment by Roger-Sh** [comment]
> * Ubuntu: 16.06
> * compile install
> 
> I compiled the package from source and it can be successfully compiled, However, when I run the python examples, it throws error:
> 
> ```
> /openravepy/_openravepy_/convexdecompositionpy.so: undefined symbol: _ZTIN8OpenRAVE17OpenRAVEExceptionE
> /openravepy/_openravepy_/pyANN_int.so: undefined symbol: _ZTIN8OpenRAVE17OpenRAVEExceptionE
> ```
> 
> How to fix this?
> 
> Thanks,

Hi, have you solved this problem?
