### ISSUE TITLE
Incompatibility in inversekinematics.py when compiled with pybind11

### ISSUE THREAD

**Issue by hungpham2511** [rdiankov/openrave#963]
It seems like when openrave is compiled with pybind11, the following lines in inversekinematics.py break:

https://github.com/rdiankov/openrave/blob/ec02e7ceda3d08e778ad88a0fe298b715a4253bb/python/databases/inversekinematics.py#L1130-L1133

and 

https://github.com/rdiankov/openrave/blob/ec02e7ceda3d08e778ad88a0fe298b715a4253bb/python/databases/inversekinematics.py#L1118

The reason is that enum in pybind11 does not expose `.values` and `.name` methods.

**Comment by hungpham2511** [comment]
It seems like pybind11 enum also produces a different string representation of the enum value: https://github.com/rdiankov/openrave/blob/ec02e7ceda3d08e778ad88a0fe298b715a4253bb/python/databases/inversekinematics.py#L592

**Comment by cielavenir** [comment]
for `str(self.iktype) and `iktype.name`, https://github.com/cielavenir/pybind11/commit/dae2d434bd806eac67e38f3c49cfc91f46e4fd88 would be helpful.

I will take a look at `IkParameterizationType.values` when I have time.

**Comment by hungpham2511** [comment]
Cool. This fix should work. 

Look like the `.values.` should return the same as the `__members__` attribute.

**Comment by cielavenir** [comment]
https://github.com/cielavenir/pybind11/commit/2e08ce9ba75f5a2d87a6f12e6ab657ac78444e8e should fix it

**Comment by cielavenir** [comment]
if you still have issues with my patch, please let me know.

note that the patch is already integrated in https://github.com/cielavenir/mujin_recruiting/blob/pybind11/cookbooks/mujin/recipes/default.rb .

**Comment by hungpham2511** [comment]
Thanks! It does. 

Btw, I am just curious, will OpenRAVE provides support for python3 binding at any point in the future?

**Comment by cielavenir** [comment]
see https://github.com/rdiankov/openrave/pull/979
